### ISSUE TITLE
DM-1801 - ID out of range when giving lengthy Talk Group IDs.

### ISSUE THREAD

**Issue by qmsarge** [forkoz/radioddity_gd-77_cps#1]
I downloaded DM1801-CPS.v.07.zip onto my Windows 10 PC. I ran into an error when I tried to configure a Digital Contact. This is for a Talk Group with ID 16777184. I get the error "ID out of range". Is there a limitation on the ID? Can that be over come?

I am yet to receive the programming cable. But I tried creating a "Personal" (i.e not Talk Group) contact using the keypad. It did take the DMR ID of 16777184. I am attaching a screen image of the error I am getting. Is there any settings which I am missing here? Note, I am still setting up the code plug and have not made any connections between the PC and the radio. I have also not changed the firmware on the radio.

NOTE: I have tried to install the DM1801-CPS from multiple sources, all of them had this very same problem. My understanding is that talk group IDs can extend up to 16777215.
![CPS_v 07_Error](https://user-images.githubusercontent.com/51510621/59148217-7e5ca500-8a23-11e9-87ca-75a67fd48948.jpg)

**Comment by forkoz** [comment]
DMR Id goes into contacts not talk group. If you make that a private call it should work. TG should be something like 8000, 3000, etc.

**Comment by qmsarge** [comment]
> DMR Id goes into contacts not talk group. If you make that a private call it should work. 
>TG should be something like 8000, 3000, etc.
Thank you for checking up my report. I did some research. Looks like 16777184 is one of those restricted TalkGroups as per ETSI standards. They are generally not to be used as IDs for any contacts or talk groups. Though I understand some scanners allow talk groups to be created with such IDs. But looks like that is not possible in DB-1801.
